// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: common.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Onlineproto
{

    [global::ProtoBuf.ProtoContract(Name = @"G_Player")]
    public partial class GPlayer
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public long Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"exp")]
        public int Exp { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int vipLv { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"E_ErrorCode")]
    public enum EErrorCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NO_ERROR")]
        NoError = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIN_ON_OTHER_DEVICE")]
        LoginOnOtherDevice = 1,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
